
[font]
size = 10.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false

[window.dimensions]
columns = 100
lines = 200

[window.padding]
x = 0
y = 0

[general]
# import = ["/home/embercraze/.config/alacritty/alacritty-theme/themes/gruvbox_material.toml"]
# import = ["/home/embercraze/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]
import = ["/home/embercraze/.config/alacritty/alacritty-theme/themes/one_light.toml"]
