[theme]
theme = "native"
[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
interval = 1
# display_type = "memory"
# format_mem = "{mem_used_percents}"
# format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{$barchart} {$utilization |} {$frequency}"

[[block]]
block = "sound"
show_volume_when_muted = true
driver = "auto"
# format = "{volume}"
# on_click = "pavucontrol"
step_width = 3
max_vol = 150
[[block.click]]
button="left"
cmd="pavucontrol"

[[block]]
block = "battery"
full_format = " $icon $percentage "
format = "$percentage est {$time |}"
missing_format = " $icon Battery missing"
empty_format = "$percentage est {$time |} Charge ASAP" 
empty_threshold = 10
full_threshold = 80

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'%a %d %b %R') "
