[theme]
theme = "native"
[icons]
icons = "awesome6"

[[block]]
block = "custom"
command = "xkb-switch"
interval = 1

[[block]]
block = "custom"
cycle = ["python ~/.config/i3status-rust/scripts/next-prayer.py strangnas sweden",  "python ~/.config/i3status-rust/scripts/next-prayer.py stockholm sweden"]
interval = 60

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
# format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 1
chip = "*-isa-*"

[[block]]
block = "cpu"
interval = 1
format = "$barchart $utilization.eng(w:3) $frequency.eng(w:4)"

[[block]]
block = "sound"
show_volume_when_muted = true
driver = "auto"
# format = "{volume}"
# on_click = "pavucontrol"
step_width = 3
max_vol = 150
[[block.click]]
button="left"
cmd="pavucontrol"

[[block]]
block = "battery"
full_format = " $icon $percentage "
format = "$percentage est {$time |}"
missing_format = "Battery missing"
empty_format = "$percentage est {$time |} CHARGE ASAP"
empty_threshold = 10
full_threshold = 80

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'%a %d %b %R') "
